# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 788533cd235cc9f6833cf4377f278b464768e4ff91ed0425258251d6a512c58aca27005122f106bc514fd9744cfc9f52fedf156cee150bb9738d52badd40b7e6

test:
  secret_key_base: 0a69f5cba8d67084e3004d3e761350eed0c24f7cd376b560750164d6a9ccf2e45d8d68b239ca877171f8461e382cbe320e14eb08435e02edc55becc53f7306a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
